In [80]:
import numpy as np
import pandas as pd
import seaborn as sb

In [58]:
x = [[1,2,3],[4,5,6],[7,8,9]]
y = np.array(x)
max = y.max()
min = y.min()

print(x)
print(f'Max={max}, Min=(min)')
print()
print(y)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Max=9, Min=(min)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
#random values
a = np.random.rand(3)
b = np.random.randn(3) #negatif values
c = np.random.randint(1,100) #random value 1 between 100
d = y.argmax()
e = y.argmin()

print(a)
print(b)
print(f'Random 1-100={c}, RandomMaxArgue={d}, RandomMinArgue={e}')

[0.88129312 0.19667342 0.86524581]
[-1.51031808  0.72321744 -0.32019638]
Random 1-100=76, RandomMaxArgue=8, RandomMinArgue=0


In [9]:
x = [[[1,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]]]
y = np.array(x)

print(x)
print()
print(y)

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [30]:
a = np.zeros(3)
b = np.zeros(3) + 5
c = np.zeros((2,3))
d = np.ones((2,3))
e = np.eye(4)

print(f'A={a}, B={b}')
print()
print(c)
print()
print(d)
print()
print(e)

A=[0. 0. 0.], B=[5. 5. 5.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [68]:
a = np.arange(10)
b = np.arange(3,10)
c = np.arange(12).reshape(3,4)
d = np.arange(10,22).reshape(3,4)

print(a)
print(b)
print()
print(c)
print()
print(c+d)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [48]:
#linear space
a = np.linspace(0,10)
b = np.linspace(0,100,5)

print(a)
print(f'B = {b}')

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
B = [  0.  25.  50.  75. 100.]


In [6]:
x = np.array([1,1,2,3,4,5,6])
y = np.array([0,2,1,3,4,8,9])

# How to get the common in between these two arrays
np.intersect1d(x,y)

array([1, 2, 3, 4])

In [7]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Test Using Pandas

x = ['a', 'b', 'c', 'd', 'e']
y = [1, 2, 3, 4, 5]
z = {1:'a', 2:'b', 3:'c', 4:'d', 5:'e'}

In [9]:
pd.Series(x)

0    a
1    b
2    c
3    d
4    e
dtype: object

In [10]:
A = ['😊','😂','🤣','❤']
B = ['😊','😂','🤣','❤']
C = ['😊','😂','🤣','❤']
D = ['😊','😂','🤣','❤']
E = ['😊','😂','🤣','❤']

In [13]:
df = pd.DataFrame([A,B,C,D,E], ['a','b','c','d','e'], ['W','X','Y','Z'])
df['Other'] = df['Y'] + df['Z']
df

W  X  Y  Z Other
a  😊  😂  🤣  ❤    🤣❤
b  😊  😂  🤣  ❤    🤣❤
c  😊  😂  🤣  ❤    🤣❤
d  😊  😂  🤣  ❤    🤣❤
e  😊  😂  🤣  ❤    🤣❤

In [72]:
a = {'a':[1,2,3,4,5],
     'b':[6,7,8,9,np.nan],
     'c':[0,1,2,np.nan,np.nan],
     'd':[3,4,np.nan,np.nan,np.nan],
     'e':[5,np.nan,np.nan,np.nan,np.nan]
     }

In [73]:
df = pd.DataFrame(a)
df

a    b    c    d    e
0  1  6.0  0.0  3.0  5.0
1  2  7.0  1.0  4.0  NaN
2  3  8.0  2.0  NaN  NaN
3  4  9.0  NaN  NaN  NaN
4  5  NaN  NaN  NaN  NaN

In [75]:
pd.concat([df])

a    b    c    d    e
0  1  6.0  0.0  3.0  5.0
1  2  7.0  1.0  4.0  NaN
2  3  8.0  2.0  NaN  NaN
3  4  9.0  NaN  NaN  NaN
4  5  NaN  NaN  NaN  NaN

Read CSV!!!

In [78]:
pd.read_csv('tips.csv')

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [81]:
sb.load_dataset('tips')

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]