In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
x = np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
x = np.arange(12).reshape(3,4)
y = np.arange(10,22).reshape(3,4)

x+y

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [5]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x = np.array([1,1,2,3,4,5,6])
y = np.array([0,2,1,3,4,8,9])

# How to get the common in between these two arrays
np.intersect1d(x,y)

array([1, 2, 3, 4])

In [7]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Test Using Pandas

x = ['a', 'b', 'c', 'd', 'e']
y = [1, 2, 3, 4, 5]
z = {1:'a', 2:'b', 3:'c', 4:'d', 5:'e'}

In [9]:
pd.Series(x)

0    a
1    b
2    c
3    d
4    e
dtype: object

In [10]:
A = ['😊','😂','🤣','❤']
B = ['😊','😂','🤣','❤']
C = ['😊','😂','🤣','❤']
D = ['😊','😂','🤣','❤']
E = ['😊','😂','🤣','❤']

In [13]:
df = pd.DataFrame([A,B,C,D,E], ['a','b','c','d','e'], ['W','X','Y','Z'])
df['Other'] = df['Y'] + df['Z']
df

W  X  Y  Z Other
a  😊  😂  🤣  ❤    🤣❤
b  😊  😂  🤣  ❤    🤣❤
c  😊  😂  🤣  ❤    🤣❤
d  😊  😂  🤣  ❤    🤣❤
e  😊  😂  🤣  ❤    🤣❤

In [3]:
a = {'a':[1,2,3,4,5],
     'b':[6,7,8,9,np.nan],
     'c':[0,1,2,np.nan,np.nan],
     'd':[3,4,np.nan,np.nan,np.nan],
     'e':[5,np.nan,np.nan,np.nan,np.nan]
     }

In [4]:
df = pd.DataFrame(a)
df

a    b    c    d    e
0  1  6.0  0.0  3.0  5.0
1  2  7.0  1.0  4.0  NaN
2  3  8.0  2.0  NaN  NaN
3  4  9.0  NaN  NaN  NaN
4  5  NaN  NaN  NaN  NaN

In [6]:
pd.concat(df)

TypeError: concat() missing 1 required positional argument: 'objs'